### ISSUE TITLE
Read php-semver-checker-git.yaml configuration file by default

### ISSUE THREAD

**Issue by tomzx** [tomzx/php-semver-checker-git#15]
* If a php-semver-checker-git.json file is found in the current working directory, read it as the configuration file.
* If a configuration option is given to the command line, this configuration file takes precedence over the one in the current working directory.
* Finally, any option given on the command line overrides what is in the configuration file.

**Comment by nochso** [comment]
Almost with this. See related: tomzx/php-semver-checker#72
