### ISSUE TITLE
Empty releases for latest release link

### ISSUE THREAD

**Issue by mallardduck** [tomzx/php-semver-checker-git#31]
Per the title, when you currently load: http://psvcg.coreteks.org/php-semver-checker-git.phar
The download is simple the shebang for bash to load it as PHP.

**Comment by tomzx** [comment]
Hello @mallardduck, thanks for pointing out the issue. I've corrected the server configuration and this should be resolved.
Feel free to reopen this ticket if it still isn't fixed on your end.

**Comment by mallardduck** [comment]
Thanks for the quickfix @tomzx! Looks good now. Thanks!
